### ISSUE TITLE
nvs_[get/set]_u[8/16] not working

### ISSUE THREAD

**Issue by Roosted7** [SHA2017-badge/micropython-esp32#93] opened 2017-07-22 18:46 UTC
Nice to store ints in the NVS, but current code just crashes

**Comment by annejan** [comment] 2017-07-22 18:47
Can't reproduce . .

**Comment by Roosted7** [comment] 2017-07-22 18:52
Okay, if memory serves me well tsd also had this issue.
(His badge crashed before he reverted renze his commit that started using int instead of str)

**Comment by annejan** [comment] 2017-07-22 18:59
Ah, might it be that the values are stored as string, but attempt to retrieve as int? 

That would make it a legacy data issue.

**Comment by Roosted7** [comment] 2017-07-22 19:01
Ah could be.. My badge crashes when trying the get or set the voltage levels for the battery(bar)

**Comment by basvs** [comment] 2017-07-23 09:27
I also got crashes when i requested unset entries. I will dive into this

**Comment by basvs** [comment] 2017-07-23 10:50
>>> badge.nvs_get_u8("lalala", "lala", 42)
42
>>> badge.nvs_get_u8("lalala", "lala")
Guru Meditation Error of type LoadProhibited occurred on core  0. Exception was unhandled.

**Comment by basvs** [comment] 2017-07-23 10:51
The code works when you use a default. If not, you will get a null-pointer-exception.

I have a patch ready.

**Comment by basvs** [comment] 2017-07-23 11:11
We cannot merge this yet. It triggers bugs in other scripts. Have to fix that first.. :)

**Comment by basvs** [comment] 2017-07-23 13:22
scripts are fixed; code is merged.

**Closed as completed by basvs** 2017-07-23 13:22 UTC
